name: deaftv_lgdxschool_projects
description: "LG TV 데모용 Flutter 웹 앱"
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  video_player: ^2.8.2
  web_socket_channel: ^2.4.0

  flutter_dotenv: ^5.1.0

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_database: ^11.1.4
  firebase_remote_config: ^5.1.3
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/LG_logo.png
    - assets/일반.png
    - assets/청각.png
    - assets/시각.png
    - assets/아동.png
    - assets/시니어.png
    - assets/일반-1.png
    - assets/청각-1.png
    - assets/시각-1.png
    - assets/아동-1.png
    - assets/시니어-1.png
    - assets/home_background.png
    - assets/settings_image.png
    - assets/가_none.png
    - assets/가_basic.png
    - assets/가_wide.png
    - assets/가_middle.png
    - assets/quick_image.png
    - assets/palette_1.png
    - assets/palette_2.png
    - assets/palette_3.png
    - assets/qr_code.png
    - assets/guide_shake.png  
    - assets/mode_guide.png
    - assets/general_preview.mp4
    - assets/drama_preview.mp4
    - assets/dacu_preview.mp4
    - assets/date_preview.mp4
    - assets/1speak_guide.png
    - assets/2color_guide.png
    - assets/3speaker_guide.png
    - assets/4back_guide.png
    - assets/인사이드아웃.mp4
    - assets/인사이드아웃.wav
    - assets/친애하는x.mp4
    - assets/친애하는x.wav
    - assets/펭귄다큐_0_3분.mp4
    - assets/펭귄다큐_0_3분.wav
    - assets/환승연애5_2분.mp4
    - assets/환승연애5_2분.wav
    - assets/dacu2.mp4
    - assets/dacu2.wav
    - assets/drama.mp4
    - assets/drama.wav
    - assets/enter_web.mp4
    - assets/enter_web.wav
    - assets/setting_preview.png